CREATE SEQUENCE dbo.ClientSeq
    START WITH 1
    INCREMENT BY 50;
GO

CREATE TABLE dbo.Client
(
    Id          BIGINT       NOT NULL,
    CreatedAt   DATETIME     NOT NULL,
    UpdatedAt   DATETIME     NOT NULL,
    Name        VARCHAR(255) NOT NULL,
    CompanyId   VARCHAR(255),
    Description VARCHAR(255),
    CONSTRAINT PK_Client PRIMARY KEY (Id)
);
GO

CREATE SEQUENCE dbo.SiteSeq
    START WITH 1
    INCREMENT BY 50;
GO

CREATE TABLE dbo.Site
(
    Id         BIGINT       NOT NULL,
    CreatedAt  DATETIME     NOT NULL,
    UpdatedAt  DATETIME     NOT NULL,
    Name       VARCHAR(255) NOT NULL,
    PropertyId VARCHAR(255) NOT NULL,
    ClientId   BIGINT       NOT NULL,
    CONSTRAINT Pk_Site PRIMARY KEY (Id)
)
GO

ALTER TABLE dbo.Client
    ADD CONSTRAINT UC_CLIENT_COMPANYID UNIQUE (CompanyId)
GO

ALTER TABLE dbo.Site
    ADD CONSTRAINT UC_SITE_PROPERTYID_CLIENTID UNIQUE (PropertyId, ClientId)
GO

ALTER TABLE dbo.Site
    ADD CONSTRAINT FK_SITE_ON_CLIENTID FOREIGN KEY (ClientId) REFERENCES dbo.Client (Id)
GO
