### Hello
GET {{root}}/api/hello?name=XYZ
Authorization: Bearer {{mytoken}}

### Clients
GET {{root}}/api/clients
Authorization: Bearer {{mytoken}}

###
POST {{root}}/api/clients
Content-Type: application/json
Authorization: Bearer {{mytoken}}

{
  "name": "ACME",
  "companyId": "CoolId"
}

### Sites
GET {{root}}/api/sites
Authorization: Bearer {{mytoken}}

###
GET {{root}}/api/sites/1
Authorization: Bearer {{mytoken}}

###
GET {{root}}/api/sites/by-client/1
Authorization: Bearer {{mytoken}}

###
POST {{root}}/api/sites/with-client-id
Content-Type: application/json
Authorization: Bearer {{mytoken}}

{
  "name": "Cool Site",
  "propertyId": "CoolPropertyId",
  "clientId": 1
}

###
# non existing client
POST {{root}}/api/sites/with-client-id
Content-Type: application/json
Authorization: Bearer {{mytoken}}

{
  "name": "Cool Site",
  "propertyId": "CoolPropertyId2",
  "clientId": 2
}
